get:
  tags:
  - "roles"
  summary: "Get list of roles"
  responses:
    200:
      description: "OK"
      schema:
        type: array
        items:
          $ref: './MCenterRestApi.yaml#/definitions/Role'
    500:
      description: "Internal Server error"

post:
  tags:
  - "roles"
  summary: "Register an role"
  consumes:
  - "application/json"
  produces:
  - "application/json"
  parameters:
  - in: "body"
    name: "body"
    description: "Role detail description"
    required: true
    schema:
      $ref: './MCenterRestApi.yaml#/definitions/Role'
  responses:
    200:
      description: "OK"
      schema:
        $ref: './MCenterRestApi.yaml#/definitions/Role'
    500:
      description: "Internal Server error"
